include: package:lint/analysis_options.yaml

analyzer:
  exclude: 
    - build/**
    - "lib/**/*.g.dart"
    - "lib/**/*.freezed.dart"

linter:
  rules:
    avoid_multiple_declarations_per_line: false
    prefer_relative_imports: true # https://stackoverflow.com/a/66188522/12421326
    always_use_package_imports: false
    require_trailing_commas: false
    # Rationale: in our app, the codes are for reading on mobile phones, adding
    # `this` makes it easier for readers to understand which variables class
    # members and which ones are not.
    unnecessary_this: false
    # Same as above, allow writing local variable types to improve readability
    # without IDE.
    # We sometimes have print statements just for demo purposes.
    avoid_print: false
    omit_local_variable_types: false
    use_colored_box: false
    use_decorated_box: false
    no_leading_underscores_for_local_identifiers: false
    use_string_buffers: false
    avoid_redundant_argument_values: false
    prefer_const_constructors: false
    avoid_dynamic_calls: false
    directives_ordering: false
    sort_pub_dependencies: false