name: flutter_catalog
description: An app showcasing Flutter components, with side-by-side source code view.

version: 3.7.0+98

environment:
  sdk: ">=2.17.0 <3.0.0"

publish_to: none

dependencies:
  animated_radial_menu:
  animated_text_kit:
  animations:
  async: null
  backdrop:
  badges:
  cached_network_image:
  community_charts_flutter:
  chat_gpt_sdk: 2.0.0
  material_buttonx:
  cloud_firestore:
  cloud_firestore_web:
  community_material_icon:
  convex_bottom_bar:
  day_night_switcher:
  device_preview:
  device_preview_screenshot:
  edge_detection:
  english_words:
  extended_image:
  feature_discovery:
  ffi:
  firebase_analytics:
  firebase_analytics_web:
  firebase_auth:
  firebase_auth_web:
  firebase_core:
  firebase_core_web:
  firebase_crashlytics:
  firebase_database:
  firebase_storage:
  firebase_storage_web:
  fl_chart:
  flutter:
    sdk: flutter
  flutter_bloc:
  flutter_gallery_assets:
  flutter_heatmap_calendar:
  flutter_highlight:
  flutter_markdown:
  flutter_quill:
  flutter_radar_chart:
  flutter_riverpod:
  flutter_slidable:
  flutter_state_notifier:
  flutter_webview_plugin: ^0.4.0
  flutter_whatsnew:
    path: packages/flutter_whatsnew-master
  flutterfire_ui:
  fluttertoast:
  freezed_annotation:
  google_fonts:
  google_ml_kit:
  google_mobile_ads:
  google_sign_in:
  graphview:
  heatmap_calendar:
    git:
      url: https://github.com/CouldI/flutter_heatmap_calendar.git
  hidable:
  hive:
  hive_flutter:
  http:
  image:
  image_picker:
  in_app_purchase:
  in_app_review:
  intl:
  introduction_screen:
  like_button:
  local_auth:
  lottie:
  markdown:
  package_info_plus:
  path:
  path_provider:
  photo_view:
  provider:
  scoped_model:
  selectable:
  sembast:
  share_plus:
  shared_preferences:
  shimmer:
  sqflite:
  state_notifier:
  substring_highlight:
  super_editor:
  transparent_image:
  tuple:
  url_launcher:
  video_player:
  widget_with_codeview:
  youtube_player_iframe:

dev_dependencies:
  build_runner:
  flutter_launcher_icons:
  flutter_native_splash:
  freezed:
  hive_generator:
  json_serializable:
  lint:

# $ flutter pub run flutter_launcher_icons:main
# Cf. https://pub.dev/packages/flutter_launcher_icons
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: res/images/app_icon.png

# $ flutter pub run flutter_native_splash:create
# Cf. https://pub.dev/packages/flutter_native_splash
flutter_native_splash:
  color: "#f6f6f6"
  image: res/images/app_icon.png

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  # Note: when new assets are added, have to run `flutter clean` to see
  # changes take effect.
  assets:
    - CHANGELOG.md
    # *Tip*: keep the slash at the end of folder path adds all files to
    # assets. Note: this doesn't work with subfolders.
    # c.f. https://github.com/flutter/flutter/issues/4890#issuecomment-407327749
    - lib/routes/
    - lib/routes/data/
    - res/images/
    - res/lottie/
    - packages/flutter_gallery_assets/animated_images/animated_flutter_stickers.webp
    - screenshots/Screenshot_1541613187.png
    - screenshots/Screenshot_1541613193.png
    - screenshots/Screenshot_1541613197.png
